// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxStatus string

const (
	OutboxStatusPending    OutboxStatus = "pending"
	OutboxStatusProcessing OutboxStatus = "processing"
	OutboxStatusDone       OutboxStatus = "done"
	OutboxStatusFailed     OutboxStatus = "failed"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type IntegrationOutbox struct {
	ID             pgtype.UUID        `json:"id"`
	AggregateID    pgtype.UUID        `json:"aggregate_id"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	Status         OutboxStatus       `json:"status"`
	RetryCount     int32              `json:"retry_count"`
	IdempotencyKey string             `json:"idempotency_key"`
	LastError      pgtype.Text        `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}

type Permission struct {
	ID        pgtype.UUID        `json:"id"`
	Resource  string             `json:"resource"`
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RegistrationIdempotency struct {
	IdempotencyKey string             `json:"idempotency_key"`
	UserID         pgtype.UUID        `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type User struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
	StatusVersion             int32              `json:"status_version"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
