// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpUserStatusVersion = `-- name: BumpUserStatusVersion :one
UPDATE users
SET status_version = status_version + 1
WHERE id = $1
RETURNING status_version
`

func (q *Queries) BumpUserStatusVersion(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpUserStatusVersion, id)
	var status_version int32
	err := row.Scan(&status_version)
	return status_version, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, username, username_lookup_hash, email_lookup_hash,
    email_encrypted, email_encrypted_nonce,
    display_name_encrypted, display_name_encrypted_nonce,
    phone_encrypted, phone_encrypted_nonce,
    preferences, status, status_version, created_at, updated_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
`

type CreateUserParams struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	StatusVersion             int32              `json:"status_version"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.UsernameLookupHash,
		arg.EmailLookupHash,
		arg.EmailEncrypted,
		arg.EmailEncryptedNonce,
		arg.DisplayNameEncrypted,
		arg.DisplayNameEncryptedNonce,
		arg.PhoneEncrypted,
		arg.PhoneEncryptedNonce,
		arg.Preferences,
		arg.Status,
		arg.StatusVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const listUsersAfterCursor = `-- name: ListUsersAfterCursor :many
SELECT id, username, username_lookup_hash, email_lookup_hash,
    email_encrypted, email_encrypted_nonce,
    display_name_encrypted, display_name_encrypted_nonce,
    phone_encrypted, phone_encrypted_nonce,
    preferences, status, status_version, created_at, updated_at, deleted_at
FROM users
WHERE (
    $1::text = 'all' AND status <> 'deleted' AND deleted_at IS NULL
    OR $1::text = 'deleted' AND status = 'deleted'
    OR $1::text NOT IN ('all', 'deleted') AND status::text = $1::text AND deleted_at IS NULL
)
AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4::int
`

type ListUsersAfterCursorParams struct {
	StatusFilter    string             `json:"status_filter"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListUsersAfterCursorRow struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	StatusVersion             int32              `json:"status_version"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsersAfterCursor(ctx context.Context, arg ListUsersAfterCursorParams) ([]ListUsersAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listUsersAfterCursor,
		arg.StatusFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAfterCursorRow{}
	for rows.Next() {
		var i ListUsersAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UsernameLookupHash,
			&i.EmailLookupHash,
			&i.EmailEncrypted,
			&i.EmailEncryptedNonce,
			&i.DisplayNameEncrypted,
			&i.DisplayNameEncryptedNonce,
			&i.PhoneEncrypted,
			&i.PhoneEncryptedNonce,
			&i.Preferences,
			&i.Status,
			&i.StatusVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersFirstPage = `-- name: ListUsersFirstPage :many
SELECT id, username, username_lookup_hash, email_lookup_hash,
    email_encrypted, email_encrypted_nonce,
    display_name_encrypted, display_name_encrypted_nonce,
    phone_encrypted, phone_encrypted_nonce,
    preferences, status, status_version, created_at, updated_at, deleted_at
FROM users
WHERE (
    $1::text = 'all' AND status <> 'deleted' AND deleted_at IS NULL
    OR $1::text = 'deleted' AND status = 'deleted'
    OR $1::text NOT IN ('all', 'deleted') AND status::text = $1::text AND deleted_at IS NULL
)
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListUsersFirstPageParams struct {
	StatusFilter string `json:"status_filter"`
	PageLimit    int32  `json:"page_limit"`
}

type ListUsersFirstPageRow struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	StatusVersion             int32              `json:"status_version"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsersFirstPage(ctx context.Context, arg ListUsersFirstPageParams) ([]ListUsersFirstPageRow, error) {
	rows, err := q.db.Query(ctx, listUsersFirstPage, arg.StatusFilter, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersFirstPageRow{}
	for rows.Next() {
		var i ListUsersFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UsernameLookupHash,
			&i.EmailLookupHash,
			&i.EmailEncrypted,
			&i.EmailEncryptedNonce,
			&i.DisplayNameEncrypted,
			&i.DisplayNameEncryptedNonce,
			&i.PhoneEncrypted,
			&i.PhoneEncryptedNonce,
			&i.Preferences,
			&i.Status,
			&i.StatusVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeUserPreferences = `-- name: MergeUserPreferences :execrows
UPDATE users
SET preferences = preferences || $2::jsonb
WHERE id = $1 AND status <> 'deleted'
`

type MergeUserPreferencesParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 []byte      `json:"column_2"`
}

func (q *Queries) MergeUserPreferences(ctx context.Context, arg MergeUserPreferencesParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeUserPreferences, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceUserPreferences = `-- name: ReplaceUserPreferences :execrows
UPDATE users
SET preferences = $2::jsonb
WHERE id = $1 AND status <> 'deleted'
`

type ReplaceUserPreferencesParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 []byte      `json:"column_2"`
}

func (q *Queries) ReplaceUserPreferences(ctx context.Context, arg ReplaceUserPreferencesParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceUserPreferences, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users
SET status = 'deleted', deleted_at = now()
WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    username = $2,
    username_lookup_hash = $3,
    email_lookup_hash = $4,
    email_encrypted = $5,
    email_encrypted_nonce = $6,
    display_name_encrypted = $7,
    display_name_encrypted_nonce = $8,
    phone_encrypted = $9,
    phone_encrypted_nonce = $10,
    preferences = $11,
    status = $12,
    deleted_at = $13
WHERE id = $1
`

type UpdateUserParams struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.UsernameLookupHash,
		arg.EmailLookupHash,
		arg.EmailEncrypted,
		arg.EmailEncryptedNonce,
		arg.DisplayNameEncrypted,
		arg.DisplayNameEncryptedNonce,
		arg.PhoneEncrypted,
		arg.PhoneEncryptedNonce,
		arg.Preferences,
		arg.Status,
		arg.DeletedAt,
	)
	return err
}

const userByEmailHash = `-- name: UserByEmailHash :one
SELECT id, username, username_lookup_hash, email_lookup_hash,
    email_encrypted, email_encrypted_nonce,
    display_name_encrypted, display_name_encrypted_nonce,
    phone_encrypted, phone_encrypted_nonce,
    preferences, status, status_version, created_at, updated_at, deleted_at
FROM users
WHERE email_lookup_hash = $1
`

type UserByEmailHashRow struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	StatusVersion             int32              `json:"status_version"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UserByEmailHash(ctx context.Context, emailLookupHash []byte) (UserByEmailHashRow, error) {
	row := q.db.QueryRow(ctx, userByEmailHash, emailLookupHash)
	var i UserByEmailHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLookupHash,
		&i.EmailLookupHash,
		&i.EmailEncrypted,
		&i.EmailEncryptedNonce,
		&i.DisplayNameEncrypted,
		&i.DisplayNameEncryptedNonce,
		&i.PhoneEncrypted,
		&i.PhoneEncryptedNonce,
		&i.Preferences,
		&i.Status,
		&i.StatusVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, username, username_lookup_hash, email_lookup_hash,
    email_encrypted, email_encrypted_nonce,
    display_name_encrypted, display_name_encrypted_nonce,
    phone_encrypted, phone_encrypted_nonce,
    preferences, status, status_version, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
`

type UserByIDRow struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	StatusVersion             int32              `json:"status_version"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLookupHash,
		&i.EmailLookupHash,
		&i.EmailEncrypted,
		&i.EmailEncryptedNonce,
		&i.DisplayNameEncrypted,
		&i.DisplayNameEncryptedNonce,
		&i.PhoneEncrypted,
		&i.PhoneEncryptedNonce,
		&i.Preferences,
		&i.Status,
		&i.StatusVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userByUsernameHash = `-- name: UserByUsernameHash :one
SELECT id, username, username_lookup_hash, email_lookup_hash,
    email_encrypted, email_encrypted_nonce,
    display_name_encrypted, display_name_encrypted_nonce,
    phone_encrypted, phone_encrypted_nonce,
    preferences, status, status_version, created_at, updated_at, deleted_at
FROM users
WHERE username_lookup_hash = $1
`

type UserByUsernameHashRow struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	UsernameLookupHash        []byte             `json:"username_lookup_hash"`
	EmailLookupHash           []byte             `json:"email_lookup_hash"`
	EmailEncrypted            []byte             `json:"email_encrypted"`
	EmailEncryptedNonce       []byte             `json:"email_encrypted_nonce"`
	DisplayNameEncrypted      []byte             `json:"display_name_encrypted"`
	DisplayNameEncryptedNonce []byte             `json:"display_name_encrypted_nonce"`
	PhoneEncrypted            []byte             `json:"phone_encrypted"`
	PhoneEncryptedNonce       []byte             `json:"phone_encrypted_nonce"`
	Preferences               []byte             `json:"preferences"`
	Status                    string             `json:"status"`
	StatusVersion             int32              `json:"status_version"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UserByUsernameHash(ctx context.Context, usernameLookupHash []byte) (UserByUsernameHashRow, error) {
	row := q.db.QueryRow(ctx, userByUsernameHash, usernameLookupHash)
	var i UserByUsernameHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameLookupHash,
		&i.EmailLookupHash,
		&i.EmailEncrypted,
		&i.EmailEncryptedNonce,
		&i.DisplayNameEncrypted,
		&i.DisplayNameEncryptedNonce,
		&i.PhoneEncrypted,
		&i.PhoneEncryptedNonce,
		&i.Preferences,
		&i.Status,
		&i.StatusVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
