// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

// One row of a tenant's agent-credential registry (mirrors AgentCredentialDTO).
type AgentCredential struct {
	ID      string `json:"id"`
	AgentID string `json:"agentId"`
	// The person answerable for what this agent writes (ADR-013 §2).
	PrincipalID string `json:"principalId"`
	// Copied off the minter — an agent cannot ask for a role (補裁 O-3).
	TenantRole   string   `json:"tenantRole"`
	AllowedTypes []string `json:"allowedTypes"`
	ExpiresAt    string   `json:"expiresAt"`
	RevokedAt    *string  `json:"revokedAt,omitempty"`
	CreatedAt    string   `json:"createdAt"`
	// Computed by the domain API and passed through, not re-derived here.
	//
	// `revokedAt == null` and "usable" are different questions: a credential that
	// expired last week is not revoked and is not active. Deriving this in the BFF
	// would put a second clock in the room, and the one that decides whether the
	// next request is refused is not this one.
	Active bool `json:"active"`
}

type AuthPayload struct {
	User         *User  `json:"user"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int    `json:"expiresIn"`
	TokenType    string `json:"tokenType"`
}

type CreateNotificationInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type CreatePlatformAppInput struct {
	Name     string  `json:"name"`
	TenantID string  `json:"tenantId"`
	Owner    *string `json:"owner,omitempty"`
}

type IssueAgentCredentialInput struct {
	AgentID string `json:"agentId"`
	// The role the credential will carry, bounded by the CALLER's own role
	// (ADR-013 補裁 S-1): owner may grant admin/editor/viewer, admin may grant
	// editor/viewer, and neither may grant its own.
	//
	// Non-null but may be empty, for the same reason allowedTypes is: which values
	// are legal depends on the caller, so the refusal belongs to the domain service
	// and a schema-level enum here would be a second copy of a table that changes.
	TenantRole string `json:"tenantRole"`
	// Non-null but may be empty: an ABSENT list and an EMPTY list must produce the
	// same refusal in the same voice, and that answer lives in the domain service.
	// Making this `[String!]!` and letting `[]` through keeps it there.
	AllowedTypes []string `json:"allowedTypes"`
}

// The mint response — the ONLY time the token is ever returned.
//
// `agent_credentials` stores neither the token nor a hash of it (補裁 O-1), so
// there is no second chance to read it and no field that could offer one.
type IssuedAgentCredential struct {
	ID           string   `json:"id"`
	Token        string   `json:"token"`
	AgentID      string   `json:"agentId"`
	AllowedTypes []string `json:"allowedTypes"`
	ExpiresAt    string   `json:"expiresAt"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Notification struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Read      bool   `json:"read"`
	CreatedAt string `json:"createdAt"`
}

type PlatformAlert struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	AlertType string `json:"alertType"`
	Read      bool   `json:"read"`
	CreatedAt string `json:"createdAt"`
}

type PlatformApp struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TenantID  string `json:"tenantId"`
	Owner     string `json:"owner"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type PlatformAppConnection struct {
	Items  []*PlatformApp `json:"items"`
	Total  int            `json:"total"`
	Limit  int            `json:"limit"`
	Offset int            `json:"offset"`
}

type PlatformBillingSummary struct {
	PlanName      string `json:"planName"`
	RenewsAt      string `json:"renewsAt"`
	PaymentStatus string `json:"paymentStatus"`
	AppsUsed      int    `json:"appsUsed"`
	AppsQuota     int    `json:"appsQuota"`
	SeatsUsed     int    `json:"seatsUsed"`
	SeatsQuota    int    `json:"seatsQuota"`
}

type PlatformInvoice struct {
	ID       string `json:"id"`
	IssuedAt string `json:"issuedAt"`
	Amount   string `json:"amount"`
	Status   string `json:"status"`
}

type PlatformMutations struct {
	CreateApp       *PlatformApp `json:"createApp"`
	UpdateAppStatus *PlatformApp `json:"updateAppStatus"`
}

// Platform operator console (apps, billing, staff, ops KPI).
type PlatformOps struct {
	Apps     *PlatformAppConnection  `json:"apps"`
	Billing  *PlatformBillingSummary `json:"billing"`
	Invoices []*PlatformInvoice      `json:"invoices"`
	Staff    []*PlatformStaffMember  `json:"staff"`
	Alerts   []*PlatformAlert        `json:"alerts"`
	Reports  *PlatformReportsSummary `json:"reports"`
}

type PlatformReportsSummary struct {
	Mrr        string `json:"mrr"`
	ActiveApps int    `json:"activeApps"`
	PausedApps int    `json:"pausedApps"`
}

type PlatformStaffMember struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

type Query struct {
}

type RegisterInput struct {
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
	DisplayName *string `json:"displayName,omitempty"`
}

type Ticket struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type TicketConnection struct {
	Items  []*Ticket `json:"items"`
	Total  int       `json:"total"`
	Limit  int       `json:"limit"`
	Offset int       `json:"offset"`
}

type User struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Email       *string `json:"email,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Status      string  `json:"status"`
}

// Authenticated end-user scope (profile, personal notifications).
type Viewer struct {
	Me            *User           `json:"me"`
	Notifications []*Notification `json:"notifications"`
}
