package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input RegisterInput) (*AuthPayload, error) {
	body := map[string]any{
		"username": input.Username,
		"email":    input.Email,
		"password": input.Password,
	}
	if input.DisplayName != nil {
		body["display_name"] = *input.DisplayName
	}
	if _, err := r.Client.Register(ctx, body); err != nil {
		return nil, mapAPIError(err)
	}
	tokens, err := r.Client.Login(ctx, map[string]any{
		"email":    input.Email,
		"password": input.Password,
	})
	if err != nil {
		return nil, mapAPIError(err)
	}
	return authPayloadFromLogin(ctx, r.Client, tokens)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*AuthPayload, error) {
	tokens, err := r.Client.Login(ctx, map[string]any{
		"email":    input.Email,
		"password": input.Password,
	})
	if err != nil {
		return nil, mapAPIError(err)
	}
	return authPayloadFromLogin(ctx, r.Client, tokens)
}

// CreateNotification is the resolver for the createNotification field.
func (r *mutationResolver) CreateNotification(ctx context.Context, input CreateNotificationInput) (*Notification, error) {
	bearer, err := bearerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	row, err := r.Client.CreateNotification(ctx, bearer, map[string]any{
		"title": input.Title,
		"body":  input.Body,
	})
	if err != nil {
		return nil, mapAPIError(err)
	}
	return mapNotification(row), nil
}

// Platform is the resolver for the platform field.
func (r *mutationResolver) Platform(ctx context.Context) (*PlatformMutations, error) {
	if _, err := bearerFromContext(ctx); err != nil {
		return nil, err
	}
	return &PlatformMutations{}, nil
}

// CreatePlatformApp is the resolver for the createPlatformApp field.
func (r *mutationResolver) CreatePlatformApp(ctx context.Context, input CreatePlatformAppInput) (*PlatformApp, error) {
	return createPlatformAppRecord(ctx, r.Client, input)
}

// UpdatePlatformAppStatus is the resolver for the updatePlatformAppStatus field.
func (r *mutationResolver) UpdatePlatformAppStatus(ctx context.Context, id string, status string) (*PlatformApp, error) {
	return updatePlatformAppStatusRecord(ctx, r.Client, id, status)
}

// IssueAgentCredential is the resolver for the issueAgentCredential field.
func (r *mutationResolver) IssueAgentCredential(ctx context.Context, input IssueAgentCredentialInput) (*IssuedAgentCredential, error) {
	return issueAgentCredentialRecord(ctx, r.Client, input)
}

// RevokeAgentCredential is the resolver for the revokeAgentCredential field.
func (r *mutationResolver) RevokeAgentCredential(ctx context.Context, id string) (bool, error) {
	return revokeAgentCredentialRecord(ctx, r.Client, id)
}

// CreateApp is the resolver for the createApp field.
func (r *platformMutationsResolver) CreateApp(ctx context.Context, obj *PlatformMutations, input CreatePlatformAppInput) (*PlatformApp, error) {
	return createPlatformAppRecord(ctx, r.Client, input)
}

// UpdateAppStatus is the resolver for the updateAppStatus field.
func (r *platformMutationsResolver) UpdateAppStatus(ctx context.Context, obj *PlatformMutations, id string, status string) (*PlatformApp, error) {
	return updatePlatformAppStatusRecord(ctx, r.Client, id, status)
}

// Apps is the resolver for the apps field.
func (r *platformOpsResolver) Apps(ctx context.Context, obj *PlatformOps, query *string, status *string, limit *int, offset *int) (*PlatformAppConnection, error) {
	return listPlatformApps(ctx, r.Client, query, status, limit, offset)
}

// Billing is the resolver for the billing field.
func (r *platformOpsResolver) Billing(ctx context.Context, obj *PlatformOps) (*PlatformBillingSummary, error) {
	return platformBillingSummary(ctx, r.Client)
}

// Invoices is the resolver for the invoices field.
func (r *platformOpsResolver) Invoices(ctx context.Context, obj *PlatformOps, limit *int) ([]*PlatformInvoice, error) {
	return platformInvoices(ctx, r.Client, limit)
}

// Staff is the resolver for the staff field.
func (r *platformOpsResolver) Staff(ctx context.Context, obj *PlatformOps) ([]*PlatformStaffMember, error) {
	return platformStaff(ctx, r.Client)
}

// Alerts is the resolver for the alerts field.
func (r *platformOpsResolver) Alerts(ctx context.Context, obj *PlatformOps, limit *int) ([]*PlatformAlert, error) {
	return platformAlerts(ctx, r.Client, limit)
}

// Reports is the resolver for the reports field.
func (r *platformOpsResolver) Reports(ctx context.Context, obj *PlatformOps) (*PlatformReportsSummary, error) {
	return platformReportsSummary(ctx, r.Client)
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*Viewer, error) {
	if _, err := bearerFromContext(ctx); err != nil {
		return nil, err
	}
	return &Viewer{}, nil
}

// Platform is the resolver for the platform field.
func (r *queryResolver) Platform(ctx context.Context) (*PlatformOps, error) {
	if _, err := bearerFromContext(ctx); err != nil {
		return nil, err
	}
	return &PlatformOps{}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	bearer, err := bearerFromContext(ctx)
	if err != nil {
		return nil, err
	}
	row, err := r.Client.GetUser(ctx, id, bearer)
	if err != nil {
		return nil, mapAPIError(err)
	}
	return mapUser(row), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	return viewerMe(ctx, r.Client)
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context, limit *int) ([]*Notification, error) {
	return listViewerNotifications(ctx, r.Client, limit)
}

// PlatformApps is the resolver for the platformApps field.
func (r *queryResolver) PlatformApps(ctx context.Context, query *string, status *string, limit *int, offset *int) (*PlatformAppConnection, error) {
	return listPlatformApps(ctx, r.Client, query, status, limit, offset)
}

// AgentCredentials is the resolver for the agentCredentials field.
func (r *queryResolver) AgentCredentials(ctx context.Context) ([]*AgentCredential, error) {
	return listAgentCredentials(ctx, r.Client)
}

// Me is the resolver for the me field.
func (r *viewerResolver) Me(ctx context.Context, obj *Viewer) (*User, error) {
	return viewerMe(ctx, r.Client)
}

// Notifications is the resolver for the notifications field.
func (r *viewerResolver) Notifications(ctx context.Context, obj *Viewer, limit *int) ([]*Notification, error) {
	return listViewerNotifications(ctx, r.Client, limit)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// PlatformMutations returns PlatformMutationsResolver implementation.
func (r *Resolver) PlatformMutations() PlatformMutationsResolver {
	return &platformMutationsResolver{r}
}

// PlatformOps returns PlatformOpsResolver implementation.
func (r *Resolver) PlatformOps() PlatformOpsResolver { return &platformOpsResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Viewer returns ViewerResolver implementation.
func (r *Resolver) Viewer() ViewerResolver { return &viewerResolver{r} }

type (
	mutationResolver          struct{ *Resolver }
	platformMutationsResolver struct{ *Resolver }
	platformOpsResolver       struct{ *Resolver }
	queryResolver             struct{ *Resolver }
	viewerResolver            struct{ *Resolver }
)
