package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context, limit *int, offset *int) (*TicketConnection, error) {
	return listTickets(ctx, r.Client, limit, offset)
}
