// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	service "github.com/williamlabdev/saas-forge/internal/user/service"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function with given fields: ctx, id
func (_m *MockUserService) ByID(ctx context.Context, id uuid.UUID) (*service.UserDTO, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *service.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*service.UserDTO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *service.UserDTO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type MockUserService_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserService_Expecter) ByID(ctx interface{}, id interface{}) *MockUserService_ByID_Call {
	return &MockUserService_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *MockUserService_ByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserService_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserService_ByID_Call) Return(_a0 *service.UserDTO, _a1 error) *MockUserService_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_ByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*service.UserDTO, error)) *MockUserService_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentUser provides a mock function with given fields: ctx
func (_m *MockUserService) CurrentUser(ctx context.Context) (*service.UserDTO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 *service.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.UserDTO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.UserDTO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type MockUserService_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserService_Expecter) CurrentUser(ctx interface{}) *MockUserService_CurrentUser_Call {
	return &MockUserService_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx)}
}

func (_c *MockUserService_CurrentUser_Call) Run(run func(ctx context.Context)) *MockUserService_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserService_CurrentUser_Call) Return(_a0 *service.UserDTO, _a1 error) *MockUserService_CurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_CurrentUser_Call) RunAndReturn(run func(context.Context) (*service.UserDTO, error)) *MockUserService_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserService_Expecter) Delete(ctx interface{}, id interface{}) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(_a0 error) *MockUserService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, in
func (_m *MockUserService) List(ctx context.Context, in service.ListInput) (*service.ListResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *service.ListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.ListInput) (*service.ListResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.ListInput) *service.ListResult); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ListResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.ListInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - in service.ListInput
func (_e *MockUserService_Expecter) List(ctx interface{}, in interface{}) *MockUserService_List_Call {
	return &MockUserService_List_Call{Call: _e.mock.On("List", ctx, in)}
}

func (_c *MockUserService_List_Call) Run(run func(ctx context.Context, in service.ListInput)) *MockUserService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.ListInput))
	})
	return _c
}

func (_c *MockUserService_List_Call) Return(_a0 *service.ListResult, _a1 error) *MockUserService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_List_Call) RunAndReturn(run func(context.Context, service.ListInput) (*service.ListResult, error)) *MockUserService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in
func (_m *MockUserService) Register(ctx context.Context, in service.RegisterInput) (*service.UserDTO, bool, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *service.UserDTO
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterInput) (*service.UserDTO, bool, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.RegisterInput) *service.UserDTO); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.RegisterInput) bool); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, service.RegisterInput) error); ok {
		r2 = rf(ctx, in)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in service.RegisterInput
func (_e *MockUserService_Expecter) Register(ctx interface{}, in interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, in)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, in service.RegisterInput)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.RegisterInput))
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(_a0 *service.UserDTO, _a1 bool, _a2 error) *MockUserService_Register_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(context.Context, service.RegisterInput) (*service.UserDTO, bool, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePreferences provides a mock function with given fields: ctx, id, in
func (_m *MockUserService) UpdatePreferences(ctx context.Context, id uuid.UUID, in service.PreferencesInput) (*service.UserDTO, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 *service.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, service.PreferencesInput) (*service.UserDTO, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, service.PreferencesInput) *service.UserDTO); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, service.PreferencesInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UpdatePreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePreferences'
type MockUserService_UpdatePreferences_Call struct {
	*mock.Call
}

// UpdatePreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - in service.PreferencesInput
func (_e *MockUserService_Expecter) UpdatePreferences(ctx interface{}, id interface{}, in interface{}) *MockUserService_UpdatePreferences_Call {
	return &MockUserService_UpdatePreferences_Call{Call: _e.mock.On("UpdatePreferences", ctx, id, in)}
}

func (_c *MockUserService_UpdatePreferences_Call) Run(run func(ctx context.Context, id uuid.UUID, in service.PreferencesInput)) *MockUserService_UpdatePreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(service.PreferencesInput))
	})
	return _c
}

func (_c *MockUserService_UpdatePreferences_Call) Return(_a0 *service.UserDTO, _a1 error) *MockUserService_UpdatePreferences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdatePreferences_Call) RunAndReturn(run func(context.Context, uuid.UUID, service.PreferencesInput) (*service.UserDTO, error)) *MockUserService_UpdatePreferences_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, id, in
func (_m *MockUserService) UpdateProfile(ctx context.Context, id uuid.UUID, in service.UpdateProfileInput) (*service.UserDTO, error) {
	ret := _m.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *service.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, service.UpdateProfileInput) (*service.UserDTO, error)); ok {
		return rf(ctx, id, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, service.UpdateProfileInput) *service.UserDTO); ok {
		r0 = rf(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, service.UpdateProfileInput) error); ok {
		r1 = rf(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - in service.UpdateProfileInput
func (_e *MockUserService_Expecter) UpdateProfile(ctx interface{}, id interface{}, in interface{}) *MockUserService_UpdateProfile_Call {
	return &MockUserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, id, in)}
}

func (_c *MockUserService_UpdateProfile_Call) Run(run func(ctx context.Context, id uuid.UUID, in service.UpdateProfileInput)) *MockUserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(service.UpdateProfileInput))
	})
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) Return(_a0 *service.UserDTO, _a1 error) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, service.UpdateProfileInput) (*service.UserDTO, error)) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
