// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/williamlabdev/saas-forge/internal/pkg/config"
	"github.com/williamlabdev/saas-forge/internal/user/handler"
	"github.com/williamlabdev/saas-forge/internal/user/service"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg config.User, rt config.Runtime) (*app, error) {
	pool, err := providePool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	fieldEncryptor, err := provideEncryptor(cfg)
	if err != nil {
		return nil, err
	}
	postgresRepository := provideOutboxRepository(pool)
	postgresCredentialRepository := provideCredentialRepository(pool)
	postgresRegistrationStore := provideIdempotencyStore(pool)
	postgresTenantRepository := provideTenantRepository(pool)
	postgresUserRepository := provideUserRepository(pool, fieldEncryptor, postgresRepository, postgresCredentialRepository, postgresRegistrationStore, postgresTenantRepository)
	blindIndexer, err := provideIndexer(cfg)
	if err != nil {
		return nil, err
	}
	postgresIAMRepository := provideIAMRepository(pool)
	iamService := provideIAMService(postgresIAMRepository)
	authorizer, err := provideAuthorizer(rt, iamService)
	if err != nil {
		return nil, err
	}
	signer := provideJWTSigner(rt)
	postgresAuditRepository := provideAuditRepository(pool)
	authService := provideAuthService(postgresCredentialRepository, blindIndexer, signer, iamService, postgresTenantRepository, postgresAuditRepository, rt)
	userService := service.NewUserService(postgresUserRepository, blindIndexer, authorizer, authService, postgresRegistrationStore)
	handlerHandler := handler.NewHandler(userService)
	ipLimiter := provideLoginLimiter(rt)
	registry := provideMetricsRegistry()
	handler2 := provideAuthHandler(authService, ipLimiter, registry)
	iamAdminService := provideIAMAdminService(postgresIAMRepository, authorizer)
	handler3 := provideIAMHandler(iamAdminService)
	postgresNotificationRepository := provideNotificationRepository(pool)
	notificationService := provideNotificationService(postgresNotificationRepository, authorizer)
	handler4 := provideNotificationHandler(notificationService)
	postgresPlatformAppRepository := providePlatformAppRepository(pool)
	platformAppService := providePlatformAppService(postgresPlatformAppRepository, authorizer)
	postgresPlatformConsoleRepository := providePlatformConsoleRepository(pool)
	platformConsoleService := providePlatformConsoleService(postgresPlatformConsoleRepository, authorizer)
	tenantAdminService := provideTenantAdminService(postgresTenantRepository, authorizer)
	handler5 := providePlatformAppHandler(platformAppService, platformConsoleService, tenantAdminService)
	postgresContentRepository := provideContentRepository(pool, postgresRepository)
	deliveryCounter := provideDeliveryCounter()
	store, err := provideMediaStore(rt)
	if err != nil {
		return nil, err
	}
	emailSender := provideEmailSender()
	systemNotifier := provideSystemNotifier(postgresNotificationRepository, postgresTenantRepository, emailSender)
	contentService := provideContentService(rt, postgresContentRepository, authorizer, postgresTenantRepository, deliveryCounter, store, signer, systemNotifier)
	handler6 := provideContentHandler(contentService)
	memberEmailLookup := provideUserEmailLookup(postgresUserRepository)
	tenantService := provideTenantService(postgresTenantRepository, blindIndexer, fieldEncryptor, authorizer, memberEmailLookup, postgresCredentialRepository)
	handler7 := provideTenantHandler(tenantService)
	postgresAgentCredentialRepository := provideAgentCredentialRepository(pool)
	agentCredentialService := provideAgentCredentialService(postgresAgentCredentialRepository, signer, authorizer)
	agentCredentialHandler := provideAgentCredentialHandler(agentCredentialService)
	httpHandler := provideAppRouter(handlerHandler, handler2, handler3, handler4, handler5, handler6, handler7, agentCredentialHandler, signer, rt, postgresAgentCredentialRepository, registry, pool)
	server := provideServer(cfg, httpHandler)
	client := provideMCPClient(rt)
	worker := provideOutboxWorker(postgresRepository, client, registry, rt, pool, systemNotifier)
	schedulerWorker := provideScheduler(postgresContentRepository, systemNotifier)
	mediatransformWorker := provideMediaTransform(postgresContentRepository, store)
	mainApp := &app{
		Server:          server,
		Pool:            pool,
		Worker:          worker,
		Scheduler:       schedulerWorker,
		MediaTransform:  mediatransformWorker,
		Runtime:         rt,
		IAM:             iamService,
		DeliveryCounter: deliveryCounter,
		ContentRepo:     postgresContentRepository,
	}
	return mainApp, nil
}
