// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/williamlabdev/saas-forge/internal/pkg/config"
	"github.com/williamlabdev/saas-forge/internal/user/handler"
	"github.com/williamlabdev/saas-forge/internal/user/service"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, cfg config.User, rt config.Runtime) (*app, error) {
	pool, err := providePool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	fieldEncryptor, err := provideEncryptor(cfg)
	if err != nil {
		return nil, err
	}
	postgresRepository := provideOutboxRepository(pool)
	postgresCredentialRepository := provideCredentialRepository(pool)
	postgresRegistrationStore := provideIdempotencyStore(pool)
	postgresTenantRepository := provideTenantRepository(pool)
	postgresUserRepository := provideUserRepository(pool, fieldEncryptor, postgresRepository, postgresCredentialRepository, postgresRegistrationStore, postgresTenantRepository)
	blindIndexer, err := provideIndexer(cfg)
	if err != nil {
		return nil, err
	}
	postgresIAMRepository := provideIAMRepository(pool)
	iamService := provideIAMService(postgresIAMRepository)
	authorizer, err := provideAuthorizer(rt, iamService)
	if err != nil {
		return nil, err
	}
	signer := provideJWTSigner(rt)
	postgresAuditRepository := provideAuditRepository(pool)
	authService := provideAuthService(postgresCredentialRepository, blindIndexer, signer, iamService, postgresTenantRepository, postgresAuditRepository, rt)
	userService := service.NewUserService(postgresUserRepository, blindIndexer, authorizer, authService, postgresRegistrationStore)
	handlerHandler := handler.NewHandler(userService)
	ipLimiter := provideLoginLimiter(rt)
	registry := provideMetricsRegistry()
	handler2 := provideAuthHandler(authService, ipLimiter, registry)
	iamAdminService := provideIAMAdminService(postgresIAMRepository, authorizer)
	handler3 := provideIAMHandler(iamAdminService)
	postgresNotificationRepository := provideNotificationRepository(pool)
	notificationService := provideNotificationService(postgresNotificationRepository, authorizer)
	handler4 := provideNotificationHandler(notificationService)
	postgresPlatformAppRepository := providePlatformAppRepository(pool)
	platformAppService := providePlatformAppService(postgresPlatformAppRepository, authorizer)
	postgresPlatformConsoleRepository := providePlatformConsoleRepository(pool)
	platformConsoleService := providePlatformConsoleService(postgresPlatformConsoleRepository, authorizer)
	tenantAdminService := provideTenantAdminService(postgresTenantRepository, authorizer)
	handler5 := providePlatformAppHandler(platformAppService, platformConsoleService, tenantAdminService)
	postgresTicketRepository := provideTicketRepository(pool, postgresRepository)
	ticketService := provideTicketService(postgresTicketRepository, authorizer)
	handler6 := provideTicketHandler(ticketService)
	postgresContentRepository := provideContentRepository(pool, postgresRepository)
	deliveryCounter := provideDeliveryCounter()
	store, err := provideMediaStore(rt)
	if err != nil {
		return nil, err
	}
	contentService := provideContentService(rt, postgresContentRepository, authorizer, postgresTenantRepository, deliveryCounter, store, signer)
	handler7 := provideContentHandler(contentService)
	tenantService := provideTenantService(postgresTenantRepository, blindIndexer, authorizer)
	handler8 := provideTenantHandler(tenantService)
	postgresAgentCredentialRepository := provideAgentCredentialRepository(pool)
	agentCredentialService := provideAgentCredentialService(postgresAgentCredentialRepository, signer, authorizer)
	agentCredentialHandler := provideAgentCredentialHandler(agentCredentialService)
	httpHandler := provideAppRouter(handlerHandler, handler2, handler3, handler4, handler5, handler6, handler7, handler8, agentCredentialHandler, signer, rt, postgresAgentCredentialRepository, registry)
	server := provideServer(cfg, httpHandler)
	client := provideMCPClient(rt)
	worker := provideOutboxWorker(postgresRepository, client, registry, rt, pool)
	mainApp := &app{
		Server:  server,
		Pool:    pool,
		Worker:  worker,
		Runtime: rt,
		IAM:     iamService,
	}
	return mainApp, nil
}
