// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	pagination "github.com/williamlabdev/saas-forge/internal/pkg/pagination"
	domain "github.com/williamlabdev/saas-forge/internal/user/domain"

	uuid "github.com/google/uuid"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// ByEmailHash provides a mock function with given fields: ctx, emailHash
func (_m *MockUserRepository) ByEmailHash(ctx context.Context, emailHash []byte) (*domain.User, error) {
	ret := _m.Called(ctx, emailHash)

	if len(ret) == 0 {
		panic("no return value specified for ByEmailHash")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (*domain.User, error)); ok {
		return rf(ctx, emailHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *domain.User); ok {
		r0 = rf(ctx, emailHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, emailHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ByEmailHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByEmailHash'
type MockUserRepository_ByEmailHash_Call struct {
	*mock.Call
}

// ByEmailHash is a helper method to define mock.On call
//   - ctx context.Context
//   - emailHash []byte
func (_e *MockUserRepository_Expecter) ByEmailHash(ctx interface{}, emailHash interface{}) *MockUserRepository_ByEmailHash_Call {
	return &MockUserRepository_ByEmailHash_Call{Call: _e.mock.On("ByEmailHash", ctx, emailHash)}
}

func (_c *MockUserRepository_ByEmailHash_Call) Run(run func(ctx context.Context, emailHash []byte)) *MockUserRepository_ByEmailHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockUserRepository_ByEmailHash_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_ByEmailHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ByEmailHash_Call) RunAndReturn(run func(context.Context, []byte) (*domain.User, error)) *MockUserRepository_ByEmailHash_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) ByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type MockUserRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) ByID(ctx interface{}, id interface{}) *MockUserRepository_ByID_Call {
	return &MockUserRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *MockUserRepository_ByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_ByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockUserRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// ByUsernameHash provides a mock function with given fields: ctx, usernameHash
func (_m *MockUserRepository) ByUsernameHash(ctx context.Context, usernameHash []byte) (*domain.User, error) {
	ret := _m.Called(ctx, usernameHash)

	if len(ret) == 0 {
		panic("no return value specified for ByUsernameHash")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (*domain.User, error)); ok {
		return rf(ctx, usernameHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *domain.User); ok {
		r0 = rf(ctx, usernameHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, usernameHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ByUsernameHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByUsernameHash'
type MockUserRepository_ByUsernameHash_Call struct {
	*mock.Call
}

// ByUsernameHash is a helper method to define mock.On call
//   - ctx context.Context
//   - usernameHash []byte
func (_e *MockUserRepository_Expecter) ByUsernameHash(ctx interface{}, usernameHash interface{}) *MockUserRepository_ByUsernameHash_Call {
	return &MockUserRepository_ByUsernameHash_Call{Call: _e.mock.On("ByUsernameHash", ctx, usernameHash)}
}

func (_c *MockUserRepository_ByUsernameHash_Call) Run(run func(ctx context.Context, usernameHash []byte)) *MockUserRepository_ByUsernameHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockUserRepository_ByUsernameHash_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_ByUsernameHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ByUsernameHash_Call) RunAndReturn(run func(context.Context, []byte) (*domain.User, error)) *MockUserRepository_ByUsernameHash_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, u, passwordHash, idempotencyKey
func (_m *MockUserRepository) Create(ctx context.Context, u *domain.User, passwordHash string, idempotencyKey string) error {
	ret := _m.Called(ctx, u, passwordHash, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string, string) error); ok {
		r0 = rf(ctx, u, passwordHash, idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
//   - passwordHash string
//   - idempotencyKey string
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, u interface{}, passwordHash interface{}, idempotencyKey interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, u, passwordHash, idempotencyKey)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, u *domain.User, passwordHash string, idempotencyKey string)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.User, string, string) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListPage provides a mock function with given fields: ctx, statusFilter, cursor, limit
func (_m *MockUserRepository) ListPage(ctx context.Context, statusFilter string, cursor *pagination.UserCursor, limit int) ([]*domain.User, error) {
	ret := _m.Called(ctx, statusFilter, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPage")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *pagination.UserCursor, int) ([]*domain.User, error)); ok {
		return rf(ctx, statusFilter, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *pagination.UserCursor, int) []*domain.User); ok {
		r0 = rf(ctx, statusFilter, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *pagination.UserCursor, int) error); ok {
		r1 = rf(ctx, statusFilter, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ListPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPage'
type MockUserRepository_ListPage_Call struct {
	*mock.Call
}

// ListPage is a helper method to define mock.On call
//   - ctx context.Context
//   - statusFilter string
//   - cursor *pagination.UserCursor
//   - limit int
func (_e *MockUserRepository_Expecter) ListPage(ctx interface{}, statusFilter interface{}, cursor interface{}, limit interface{}) *MockUserRepository_ListPage_Call {
	return &MockUserRepository_ListPage_Call{Call: _e.mock.On("ListPage", ctx, statusFilter, cursor, limit)}
}

func (_c *MockUserRepository_ListPage_Call) Run(run func(ctx context.Context, statusFilter string, cursor *pagination.UserCursor, limit int)) *MockUserRepository_ListPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*pagination.UserCursor), args[3].(int))
	})
	return _c
}

func (_c *MockUserRepository_ListPage_Call) Return(_a0 []*domain.User, _a1 error) *MockUserRepository_ListPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ListPage_Call) RunAndReturn(run func(context.Context, string, *pagination.UserCursor, int) ([]*domain.User, error)) *MockUserRepository_ListPage_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserDeleted provides a mock function with given fields: ctx, u
func (_m *MockUserRepository) PublishUserDeleted(ctx context.Context, u *domain.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_PublishUserDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserDeleted'
type MockUserRepository_PublishUserDeleted_Call struct {
	*mock.Call
}

// PublishUserDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockUserRepository_Expecter) PublishUserDeleted(ctx interface{}, u interface{}) *MockUserRepository_PublishUserDeleted_Call {
	return &MockUserRepository_PublishUserDeleted_Call{Call: _e.mock.On("PublishUserDeleted", ctx, u)}
}

func (_c *MockUserRepository_PublishUserDeleted_Call) Run(run func(ctx context.Context, u *domain.User)) *MockUserRepository_PublishUserDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_PublishUserDeleted_Call) Return(_a0 error) *MockUserRepository_PublishUserDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_PublishUserDeleted_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_PublishUserDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserUpdated provides a mock function with given fields: ctx, u
func (_m *MockUserRepository) PublishUserUpdated(ctx context.Context, u *domain.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_PublishUserUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserUpdated'
type MockUserRepository_PublishUserUpdated_Call struct {
	*mock.Call
}

// PublishUserUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockUserRepository_Expecter) PublishUserUpdated(ctx interface{}, u interface{}) *MockUserRepository_PublishUserUpdated_Call {
	return &MockUserRepository_PublishUserUpdated_Call{Call: _e.mock.On("PublishUserUpdated", ctx, u)}
}

func (_c *MockUserRepository_PublishUserUpdated_Call) Run(run func(ctx context.Context, u *domain.User)) *MockUserRepository_PublishUserUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_PublishUserUpdated_Call) Return(_a0 error) *MockUserRepository_PublishUserUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_PublishUserUpdated_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_PublishUserUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockUserRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockUserRepository_SoftDelete_Call {
	return &MockUserRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockUserRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_SoftDelete_Call) Return(_a0 error) *MockUserRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, u
func (_m *MockUserRepository) Update(ctx context.Context, u *domain.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, u interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, u)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, u *domain.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePreferences provides a mock function with given fields: ctx, id, prefs, merge
func (_m *MockUserRepository) UpdatePreferences(ctx context.Context, id uuid.UUID, prefs domain.Preferences, merge bool) error {
	ret := _m.Called(ctx, id, prefs, merge)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.Preferences, bool) error); ok {
		r0 = rf(ctx, id, prefs, merge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdatePreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePreferences'
type MockUserRepository_UpdatePreferences_Call struct {
	*mock.Call
}

// UpdatePreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - prefs domain.Preferences
//   - merge bool
func (_e *MockUserRepository_Expecter) UpdatePreferences(ctx interface{}, id interface{}, prefs interface{}, merge interface{}) *MockUserRepository_UpdatePreferences_Call {
	return &MockUserRepository_UpdatePreferences_Call{Call: _e.mock.On("UpdatePreferences", ctx, id, prefs, merge)}
}

func (_c *MockUserRepository_UpdatePreferences_Call) Run(run func(ctx context.Context, id uuid.UUID, prefs domain.Preferences, merge bool)) *MockUserRepository_UpdatePreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.Preferences), args[3].(bool))
	})
	return _c
}

func (_c *MockUserRepository_UpdatePreferences_Call) Return(_a0 error) *MockUserRepository_UpdatePreferences_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdatePreferences_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.Preferences, bool) error) *MockUserRepository_UpdatePreferences_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
